name: airfoil-optim-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.3.5
  - scipy=1.16.3
  - pandas
  - mpi4py=4.1.1
  - meshio=5.3.5
  - numba=0.62.1
  - pip=25.3
  - fftw
  - openmpi
  - openblas
  - lapack
